site_name: Open Project Location Model

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.follow
  custom_dir: overrides

repo_url: https://github.com/openkfw/open-geodata-model
edit_uri: edit/main/docs/

nav:
  - "index.md"
  - "Sample ToR": sample_tor.md
  - "kobo_guide.md"
  - "sdg_icons.md"
  - Tutorials:
    - "Example: Excel Template to KML": tutorials/xls_to_kml.ipynb
    - "Example: Open Geodata": tutorials/open_data_on_broadband_in_egypt.ipynb

plugins:
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - footnotes
  - toc
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
